import Head from "next/head";
import Link from "next/link";
import Avatar from "@mui/material/Avatar";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import FacebookIcon from "@mui/icons-material/Facebook";
import TwitterIcon from "@mui/icons-material/Twitter";
import LanguageIcon from "@mui/icons-material/Language";

import VerifiedIcon from "@mui/icons-material/Verified";
import Navbar from "../../components/layout/Navbar";

export default function Organization() {
  return (
    <div>
      <Head>
        <title>Organization Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxWidth="lg">
        <Box sx={{ mt: 3 }}>
          <Box sx={{ m: 1 }}>
            <Box sx={{ display: "flex", m: 2 }}>
              <Avatar variant="rounded" sx={{ width: 110, height: 110 }} />
            </Box>
            <Typography variant="h4" sx={{ m: 1 }}>
              Strathmore University
            </Typography>
            <Typography variant="body1" sx={{ m: 1 }}>
              Strathmore University Nairobi Kenya Headline Lorem ipsum dolor sit
              amet, consectetur adipiscing elit
            </Typography>
            <Box sx={{ m: 1 }}>
              <LinkedInIcon color="primary" sx={{ mr: 1 }} />
              <FacebookIcon color="primary" sx={{ mr: 1 }} />
              <TwitterIcon color="primary" sx={{ mr: 1 }} />
              <LanguageIcon color="primary" sx={{ mr: 1 }} />
            </Box>
            <Box sx={{ display: "flex", m: 1 }}>
              <Typography
                variant="subtitle1"
                color="text.secondary"
                sx={{ mr: 2 }}
              >
                378 programmes
              </Typography>
              <Typography
                variant="subtitle1"
                color="text.secondary"
                sx={{ mr: 2 }}
              >
                378900 credentials issued
              </Typography>
            </Box>
          </Box>
          <Box sx={{ display: "flex", ml: 1 }}>
            <VerifiedIcon sx={{ color: "#26c6da", m: 1 }} />
            <Typography variant="body1" sx={{ m: 1, ml: 0 }}>
              Is accredited
            </Typography>
          </Box>
          <Paper sx={{ backgroundColor: "#eeeeee", m: 2, p: 2 }}>
            <Typography variant="h5" sx={{ m: 2 }}>
              About
            </Typography>
            <Typography variant="body1" sx={{ m: 2 }}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </Typography>
          </Paper>
        </Box>
      </Container>
    </div>
  );
}
