import Head from "next/head";
import axios from "axios";
import Container from "@mui/material/Container";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import ProgrammeDetails from "../../components/programme/ProgrammeDetails";
import SearchCredential from "../../components/credential/SearchCredential";

export default function Programme({ programme }) {
  return (
    <div>
      <Head>
        <title>{programme.programme_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <AppBar position="static">
          <Toolbar>
            <IconButton
              size="large"
              edge="start"
              color="inherit"
              aria-label="menu"
              sx={{ mr: 2 }}
            >
              <MenuIcon />
            </IconButton>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              Vyeti
            </Typography>
          </Toolbar>
        </AppBar>
      </Box>
      <ProgrammeDetails programme={programme} />
      <Container maxWidth="md">
        <Box sx={{ mt: 4, ml: 1, mr: 3 }}>
          <SearchCredential />
        </Box>
      </Container>
    </div>
  );
}

export const getServerSideProps = async ({ params }) => {
  const res = await axios.get(
    `http://localhost:3000/api/programmes/${params.id}`
  );
  return {
    props: {
      programme: res.data.programme,
    },
  };
};
