import axios from "axios";
import Head from "next/head";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import { useEffect, useState } from "react";
import WalletConnect from "../../components/util/WalletConnect";
import EarnerForm from "../../components/earner/EarnerForm";
import SideSection from "../../components/layout/SideSection";
import NextButton from "../../components/util/NextButton";
import Steps from "../../components/layout/Steps";
import ErrorDisplay from "../../components/util/ErrorDisplay";
import FinishButton from "../../components/util/FinishButton";
import SuccessDisplay from "../../components/util/SuccessDisplay";

export default function Earner() {
  const [firstname, setFirstName] = useState("");
  const [lastname, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [walletaddress, setWalletAddress] = useState("");
  const [activeStep, setActiveStep] = useState(0);
  const [next, setNext] = useState(false);
  const [finish, setFinish] = useState(false);
  const [errors, setErrors] = useState([]);

  useEffect(() => {
    if (!firstname || !lastname || !email) {
      setNext(false);
    } else {
      setNext(true);
    }
  }, [firstname, lastname, email]);

  const handleNext = () => {
    const nextStep = activeStep + 1;
    setActiveStep(nextStep);
  };

  const handleBack = () => {
    const nextStep = activeStep - 1;
    setActiveStep(nextStep);
    setErrors([]);
  };

  const getWalletAddress = (address) => {
    setWalletAddress(address);
    setFinish(true);
    handleNext();
    console.log(address);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const data = {
        first_name: firstname,
        last_name: lastname,
        email: email,
        wallet: walletaddress,
      };
      await axios.post("/api/earners", data);
      console.log("success");
    } catch (err) {
      console.log(err);
      if (err) {
        setErrors(Object.values(err.response.data.errors));
      }
    }
  };
  return (
    <div>
      <Head>
        <title>Register Vyeti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container component="main" sx={{ height: "100vh" }}>
        <SideSection />
        <Grid item xs={12} sm={12} md={9} component={Paper} elevation={6}>
          <Box sx={{ m: 6 }} />
          <Container maxWidth="sm">
            <Grid align="center">
              <Typography variant="h5" sx={{}}>
                Create an Account
              </Typography>
              <Typography variant="subtitle1" color="text.secondary">
                Three simple steps to start earning digital credentials
              </Typography>
            </Grid>
            <Box sx={{ m: 4 }} />
            <Steps
              activeStep={activeStep}
              steps={["Enter Details", "Connect Wallet ", "Finish"]}
            />
            <Box sx={{ m: 4 }} />
            {activeStep === 0 ? (
              <Container maxWidth="sm">
                <EarnerForm
                  firstname={firstname}
                  lastname={lastname}
                  email={email}
                  setFirstName={setFirstName}
                  setLastName={setLastName}
                  setEmail={setEmail}
                />
                <NextButton next={next} handleNext={handleNext} />
              </Container>
            ) : (
              <Container maxWidth="sm">
                <WalletConnect setWalletAddress={getWalletAddress} />
                <SuccessDisplay
                  success={walletaddress}
                  message="Wallet Connected Successfully! Select finish to complete"
                />
                <Box sx={{ m: 4 }} />
                <Box sx={{ display: "flex" }}>
                  <Button sx={{ m: 1 }} onClick={handleBack}>
                    Back
                  </Button>
                  <FinishButton finish={finish} handleFinish={handleSubmit} />
                </Box>

                <ErrorDisplay errors={errors} />
              </Container>
            )}
          </Container>
        </Grid>
      </Grid>
    </div>
  );
}
