import Head from "next/head";
import Container from "@mui/material/Container";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import Navbar from "../components/layout/Navbar";
import Grid from "@mui/material/Grid";

export default function Home() {
  const talkingpoints = [
    "Earn Credentials",
    "Broadcast Your Skills",
    "Search For a Job",
    "Be Discovered By Employers",
    "Grow Your Skills",
  ];
  return (
    <div>
      <Head>
        <title>Vyeti </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Box sx={{ ml: 12, mr: 12, mt: 4 }}>
            <Typography
              variant="h2"
              component="h1"
              color="primary"
              sx={{ fontFamily: "Sans" }}
            >
              Level up Your <br />
              Carrer
            </Typography>
            <Typography variant="body1" sx={{ mt: 2 }}>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos
              blanditiis tenetur
            </Typography>
            {talkingpoints.map((points, index) => (
              <Box
                sx={{
                  backgroundColor: "#e3f2fd",
                  borderRadius: 2,
                  p: 1,
                  mt: 2,
                }}
                key={index}
              >
                <Typography variant="body1" sx={{ m: 1 }}>
                  {points}
                </Typography>
              </Box>
            ))}
          </Box>
        </Grid>
        <Grid item xs={6}>
          <Box sx={{ m: 2, maxWidth: 100 }}>
            <img src="image.png" style={{ maxWidth: "500px" }} />
          </Box>
        </Grid>
        <Box sx={{ m: 50 }} />
      </Grid>
    </div>
  );
}
