import Head from "next/head";
import Container from "@mui/material/Container";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import Navbar from "../components/layout/Navbar";
import Grid from "@mui/material/Grid";
// import * as React from "@types/react";
export default function Home() {
  const talkingpoints = [
    "Earn Credentials",
    "Broadcast Your Skills",
    "Search For a Job",
    "Be Discovered By Employers",
    "Grow Your Skills",
  ];
  return (
    <div>
      <Head>
        <title>Vyeti </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
            rel="stylesheet" />
      </Head>
      <Navbar />
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Box sx={{ ml: 20, mr: 12, mt: 8 }}>
            <Typography variant="h2" component="h1" fontWeight={700} fontSize={70} sx={{color:"#4D776D"}} >
              Level up your <br/>
              career
            </Typography>
            <Typography variant="body1" fontWeight={300} fontSize={33} sx={{ mt: 2 }}>
              Join millions of professionals, <br/>
              recruiters, and employers on <br/>
              Vyeti, where you can:
            </Typography>
            {talkingpoints.map((points, index) => (
              <Box
                sx={{
                  backgroundColor: "#F4FFFD",
                  borderRadius: 2,
                  p: 1,
                  mt: 2,
                  maxWidth: 500,
                }}
                key={index}
              >
                <Typography variant="body1" fontWeight={400} fontSize={20} sx={{ m: 1 }}>
                  {points}
                </Typography>
              </Box>
            ))}
          </Box>
        </Grid>
        <Grid item xs={6}>
          <Box sx={{ m: 2, maxWidth: 100 }}>
            <img src="image.png" style={{ maxWidth: "800px" }} />
          </Box>
        </Grid>
      </Grid>
    </div>
  );
}
