import axios from "axios";
import jwt from "jsonwebtoken";
import Head from "next/head";
import Container from "@mui/material/Container";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";

export default function Login() {
  const handleSubmit = async (e) => {
    e.preventDefault();
    const credentials = {
      wallet: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    };
    const res = await axios.post("/api/auth/login", credentials);
    const accounttoken = res.data.token;
    const account = jwt.decode(accounttoken);
    console.log(res);
    console.log(account);
  };
  return (
    <div>
      <Head>
        <title>Login Vyeti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <AppBar position="static">
          <Toolbar>
            <IconButton
              size="large"
              edge="start"
              color="inherit"
              aria-label="menu"
              sx={{ mr: 2 }}
            >
              <MenuIcon />
            </IconButton>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              Vyeti
            </Typography>
          </Toolbar>
        </AppBar>
        Login Page
        <button onClick={(e) => handleSubmit(e)}>Connect</button>
      </Box>
    </div>
  );
}
